name: resource_storage_hive
description: "Implementation of [ResourceStorage] for [cached_resource](https://pub.dev/packages/cached_resource) package, based on Hive and json converter."
version: 1.0.0+1
homepage: https://github.com/drstranges/resource_storage_hive
repository: https://github.com/drstranges/resource_storage_hive
issue_tracker: https://github.com/drstranges/resource_storage_hive/issues
topics:
  - storage
  - cache

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ">=2.0.0 <3.0.0"
  synchronized: ">=3.0.0 <4.0.0"
  path_provider: ">=2.1.2 <3.0.0"
  path: ">=1.6.0 <2.0.0"
  resource_storage: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_lints: ^2.0.0
